/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package professorUI;

/**
 *
 * @author apoorvdhaygude
 */
public class ProfessorAddCourseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorAddCourseJPanel
     */
    public ProfessorAddCourseJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSem = new javax.swing.JLabel();
        dropSelect = new javax.swing.JComboBox<>();
        lblCId = new javax.swing.JLabel();
        txtCId = new javax.swing.JTextField();
        lblCName = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        lblCDesc = new javax.swing.JLabel();
        txtXDesc = new javax.swing.JTextField();
        lblLang = new javax.swing.JLabel();
        txtLang = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblCredit = new javax.swing.JLabel();
        txtCredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAddCourse = new javax.swing.JButton();
        lblStrength = new javax.swing.JLabel();
        txtStrength = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("COURSE OFFERING");

        lblSem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblSem.setText("Select Semester:");

        dropSelect.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dropSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Fall 2023", "Spring 2024", "Fall 2024", "Spring 2025" }));

        lblCId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCId.setText("Course Id:");

        txtCId.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblCName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCName.setText("Course Name:");

        txtCName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });

        lblCDesc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCDesc.setText("Course Description:");

        txtXDesc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtXDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXDescActionPerformed(evt);
            }
        });

        lblLang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblLang.setText("Language:");

        txtLang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLangActionPerformed(evt);
            }
        });

        lblCost.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCost.setText("Course Cost:");

        txtCost.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });

        lblCredit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCredit.setText("Course Credit:");

        txtCredit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Back");

        btnAddCourse.setBackground(new java.awt.Color(204, 204, 0));
        btnAddCourse.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        lblStrength.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblStrength.setText("Class Strength");

        txtStrength.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStrength)
                    .addComponent(lblCredit)
                    .addComponent(lblCost)
                    .addComponent(lblLang)
                    .addComponent(lblCDesc)
                    .addComponent(lblCName)
                    .addComponent(lblCId)
                    .addComponent(lblSem))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dropSelect, 0, 156, Short.MAX_VALUE)
                    .addComponent(txtCId)
                    .addComponent(txtCName)
                    .addComponent(txtXDesc)
                    .addComponent(txtLang)
                    .addComponent(txtCost)
                    .addComponent(txtCredit)
                    .addComponent(txtStrength))
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddCourse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSem)
                    .addComponent(dropSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCId)
                    .addComponent(txtCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblCName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCDesc)
                    .addComponent(txtXDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLang)
                    .addComponent(txtLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredit)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStrength)
                    .addComponent(txtStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnAddCourse)
                .addGap(0, 98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void txtXDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXDescActionPerformed

    private void txtLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLangActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void txtCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JComboBox<String> dropSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCDesc;
    private javax.swing.JLabel lblCId;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblStrength;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCId;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtLang;
    private javax.swing.JTextField txtStrength;
    private javax.swing.JTextField txtXDesc;
    // End of variables declaration//GEN-END:variables
}
