/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package adminUI;

/**
 *
 * @author kunaltibe
 */
public class AdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminJPanel
     */
    public AdminJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfessorPerformance = new javax.swing.JButton();
        btnManageProf = new javax.swing.JButton();
        btnTranscriptAuth = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnManageStudent = new javax.swing.JButton();
        btnDegreeAuth = new javax.swing.JButton();
        btnStudentPerformance = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        btnProfessorPerformance.setBackground(new java.awt.Color(204, 204, 0));
        btnProfessorPerformance.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnProfessorPerformance.setText("Professor Performance");
        btnProfessorPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorPerformanceActionPerformed(evt);
            }
        });

        btnManageProf.setBackground(new java.awt.Color(204, 204, 0));
        btnManageProf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnManageProf.setText("Manage Professor");
        btnManageProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfActionPerformed(evt);
            }
        });

        btnTranscriptAuth.setBackground(new java.awt.Color(204, 204, 0));
        btnTranscriptAuth.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnTranscriptAuth.setText("Transcript Auth");
        btnTranscriptAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptAuthActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ADMIN DASHBOARD");

        btnBack.setBackground(new java.awt.Color(204, 204, 0));
        btnBack.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblWelcome.setText("Welcome Admin !");

        btnManageStudent.setBackground(new java.awt.Color(204, 204, 0));
        btnManageStudent.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnManageStudent.setText("Manage Student");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnDegreeAuth.setBackground(new java.awt.Color(204, 204, 0));
        btnDegreeAuth.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDegreeAuth.setText("Degree Auth");
        btnDegreeAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegreeAuthActionPerformed(evt);
            }
        });

        btnStudentPerformance.setBackground(new java.awt.Color(204, 204, 0));
        btnStudentPerformance.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnStudentPerformance.setText("Student Performance");
        btnStudentPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentPerformanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblWelcome))
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(btnManageProf)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStudentPerformance)
                                .addGap(48, 48, 48)
                                .addComponent(btnProfessorPerformance))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManageStudent)
                                .addGap(48, 48, 48)
                                .addComponent(btnTranscriptAuth)
                                .addGap(48, 48, 48)
                                .addComponent(btnDegreeAuth)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDegreeAuth, btnManageProf, btnManageStudent, btnProfessorPerformance, btnStudentPerformance, btnTranscriptAuth});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addComponent(lblWelcome)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTranscriptAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDegreeAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStudentPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfessorPerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDegreeAuth, btnManageProf, btnManageStudent, btnProfessorPerformance, btnStudentPerformance, btnTranscriptAuth});

    }// </editor-fold>//GEN-END:initComponents

    private void btnProfessorPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfessorPerformanceActionPerformed

    private void btnManageProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageProfActionPerformed

    private void btnTranscriptAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptAuthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranscriptAuthActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnDegreeAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegreeAuthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDegreeAuthActionPerformed

    private void btnStudentPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentPerformanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentPerformanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDegreeAuth;
    private javax.swing.JButton btnManageProf;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnProfessorPerformance;
    private javax.swing.JButton btnStudentPerformance;
    private javax.swing.JButton btnTranscriptAuth;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
