/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Doctor;

/**
 *
 * @author Kunal
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    Doctor doctor;
    public DoctorJPanel(Doctor doctor) {
        initComponents();
        this.doctor = doctor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle_Doctor = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        lblOfficeAdd = new javax.swing.JLabel();
        lblDocID = new javax.swing.JLabel();
        lblSpecialize = new javax.swing.JLabel();
        lblDocContact = new javax.swing.JLabel();
        lblDocEmail = new javax.swing.JLabel();
        lblYears = new javax.swing.JLabel();
        btnSave_Doctor = new javax.swing.JButton();
        txtDocName = new javax.swing.JTextField();
        txtOfficeAdd = new javax.swing.JTextField();
        txtDocID = new javax.swing.JTextField();
        txtSpecialize = new javax.swing.JTextField();
        txtDocContact = new javax.swing.JTextField();
        txtDocEmail = new javax.swing.JTextField();
        txtYears = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lblTitle_Doctor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle_Doctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_Doctor.setText("Enter Doctor Details");

        lblDocName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocName.setText("Full Name:");

        lblOfficeAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOfficeAdd.setText("Work Address:");

        lblDocID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocID.setText("Doctor ID:");

        lblSpecialize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpecialize.setText("Specialization:");

        lblDocContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocContact.setText("Contact:");

        lblDocEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDocEmail.setText("Email:");

        lblYears.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblYears.setText("Years of Practice:");

        btnSave_Doctor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSave_Doctor.setText("Save");
        btnSave_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_DoctorActionPerformed(evt);
            }
        });

        txtDocEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOfficeAdd)
                    .addComponent(lblSpecialize)
                    .addComponent(lblDocEmail)
                    .addComponent(lblDocContact)
                    .addComponent(lblDocName)
                    .addComponent(lblDocID)
                    .addComponent(lblYears))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave_Doctor)
                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocContact, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOfficeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpecialize, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addComponent(lblTitle_Doctor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle_Doctor)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocName)
                    .addComponent(txtDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocContact)
                    .addComponent(txtDocContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocEmail)
                    .addComponent(txtDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfficeAdd)
                    .addComponent(txtOfficeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpecialize)
                    .addComponent(txtSpecialize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYears))
                .addGap(18, 18, 18)
                .addComponent(btnSave_Doctor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocEmailActionPerformed

    private void btnSave_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_DoctorActionPerformed
        // TODO add your handling code here:
        doctor.setDoctorId(txtDocID.getText());
        doctor.setDocName(txtDocName.getText());
        doctor.setDocContact(txtDocContact.getText());
        doctor.setDocEmail(txtDocEmail.getText());
        doctor.setOfficeAdd(txtOfficeAdd.getText());
        doctor.setSpecialty(txtSpecialize.getText());
        doctor.setDocYears(txtYears.getText());
        
        JOptionPane.showMessageDialog(this,"Doctor Details are saved");
    }//GEN-LAST:event_btnSave_DoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave_Doctor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocContact;
    private javax.swing.JLabel lblDocEmail;
    private javax.swing.JLabel lblDocID;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblOfficeAdd;
    private javax.swing.JLabel lblSpecialize;
    private javax.swing.JLabel lblTitle_Doctor;
    private javax.swing.JLabel lblYears;
    private javax.swing.JTextField txtDocContact;
    private javax.swing.JTextField txtDocEmail;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtOfficeAdd;
    private javax.swing.JTextField txtSpecialize;
    private javax.swing.JTextField txtYears;
    // End of variables declaration//GEN-END:variables
}
