/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.InsuranceCoverage;

/**
 *
 * @author Kunal
 */
public class InsuranceCoverageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceCoverageJPanel
     */
    InsuranceCoverage insurance;
    public InsuranceCoverageJPanel(InsuranceCoverage insurance) {
        initComponents();
        this.insurance = insurance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTitle_Insurance = new javax.swing.JLabel();
        btnSave_Insurance = new javax.swing.JButton();
        lblCorporateID = new javax.swing.JLabel();
        lblCorporateAdd = new javax.swing.JLabel();
        lblPremium = new javax.swing.JLabel();
        lblDeductable = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        txtCorporateID = new javax.swing.JTextField();
        txtCorporateAdd = new javax.swing.JTextField();
        txtPremium = new javax.swing.JTextField();
        txtDeductable = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaBenefits = new javax.swing.JTextArea();
        lblPlanName = new javax.swing.JLabel();
        txtPlanName = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lblTitle_Insurance.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle_Insurance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_Insurance.setText("Insurance Coverage Information");

        btnSave_Insurance.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSave_Insurance.setText("Save");
        btnSave_Insurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_InsuranceActionPerformed(evt);
            }
        });

        lblCorporateID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorporateID.setText("Corporate ID:");

        lblCorporateAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorporateAdd.setText("Address:");

        lblPremium.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPremium.setText("Premium:");

        lblDeductable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDeductable.setText("Deductable:");

        lblBenefits.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBenefits.setText("Benefits:");

        txtareaBenefits.setColumns(20);
        txtareaBenefits.setRows(5);
        txtareaBenefits.setText("1. This plan ensures that policyholders have access to the medical care they need \n    without the burden of high out-of-pocket costs, promoting peace of mind and \n    financial security.\n2. Policyholders under HealthGuard Plus have access to an extensive network of \n    healthcare providers, including hospitals, clinics, specialists, and primary care \n    physicians.");
        jScrollPane1.setViewportView(txtareaBenefits);

        lblPlanName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlanName.setText("Plan Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle_Insurance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorporateAdd)
                                    .addComponent(lblPlanName)
                                    .addComponent(lblBenefits)))
                            .addComponent(lblCorporateID))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnSave_Insurance))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorporateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPremium)
                            .addComponent(lblDeductable))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle_Insurance)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateID)
                    .addComponent(txtCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremium)
                    .addComponent(txtPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeductable)
                    .addComponent(txtDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorporateAdd)
                    .addComponent(txtCorporateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlanName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBenefits))
                .addGap(18, 18, 18)
                .addComponent(btnSave_Insurance)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave_InsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_InsuranceActionPerformed
        // TODO add your handling code here:
        insurance.setCorporateID(txtCorporateID.getText());
        insurance.setPremium(txtPremium.getText());
        insurance.setDeductable(txtDeductable.getText());
        insurance.setCorporateAdd(txtCorporateAdd.getText());
        insurance.setPlanName(txtPlanName.getText());
        
        JOptionPane.showMessageDialog(this,"Insurance Coverage Information is saved");
    }//GEN-LAST:event_btnSave_InsuranceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave_Insurance;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblCorporateAdd;
    private javax.swing.JLabel lblCorporateID;
    private javax.swing.JLabel lblDeductable;
    private javax.swing.JLabel lblPlanName;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblTitle_Insurance;
    private javax.swing.JTextField txtCorporateAdd;
    private javax.swing.JTextField txtCorporateID;
    private javax.swing.JTextField txtDeductable;
    private javax.swing.JTextField txtPlanName;
    private javax.swing.JTextField txtPremium;
    private javax.swing.JTextArea txtareaBenefits;
    // End of variables declaration//GEN-END:variables
}
