/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Patient;

/**
 *
 * @author Kunal
 */

public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle_Patient = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPrimaryDoc = new javax.swing.JLabel();
        lblLastVisit = new javax.swing.JLabel();
        lblNextVisit = new javax.swing.JLabel();
        lblAllergies = new javax.swing.JLabel();
        lblonMedication = new javax.swing.JLabel();
        btnSave_Patient = new javax.swing.JButton();
        txtPatientID = new javax.swing.JTextField();
        txtPrimaryDoc = new javax.swing.JTextField();
        txtLastVisit = new javax.swing.JTextField();
        txtNextVisit = new javax.swing.JTextField();
        comboboxAllergies = new javax.swing.JComboBox<>();
        comboboxOnMeds = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        lblTitle_Patient.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle_Patient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_Patient.setText("Enter Patient Details");

        lblPatientID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPatientID.setText("Patient ID:");

        lblPrimaryDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrimaryDoc.setText("Primary Doctor:");

        lblLastVisit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastVisit.setText("Date of Last Visit:");

        lblNextVisit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNextVisit.setText("Date of Next Visit:");

        lblAllergies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAllergies.setText("Allergies:");

        lblonMedication.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblonMedication.setText("onMedication:");

        btnSave_Patient.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSave_Patient.setText("Save");
        btnSave_Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_PatientActionPerformed(evt);
            }
        });

        comboboxAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No" }));
        comboboxAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxAllergiesActionPerformed(evt);
            }
        });

        comboboxOnMeds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No" }));
        comboboxOnMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxOnMedsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle_Patient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPatientID)
                                .addComponent(lblPrimaryDoc)
                                .addComponent(lblLastVisit)
                                .addComponent(lblNextVisit))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAllergies, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblonMedication, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(24, 24, 24)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrimaryDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboboxOnMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboboxAllergies, 0, 100, Short.MAX_VALUE)
                                        .addComponent(txtNextVisit))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnSave_Patient)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle_Patient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimaryDoc)
                    .addComponent(txtPrimaryDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastVisit)
                    .addComponent(txtLastVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextVisit)
                    .addComponent(txtNextVisit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllergies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxOnMeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblonMedication))
                .addGap(18, 18, 18)
                .addComponent(btnSave_Patient)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxAllergiesActionPerformed
        // TODO add your handling code here:
        String selectedAValue = comboboxAllergies.getSelectedItem().toString();
        patient.setAllergies(selectedAValue);
    }//GEN-LAST:event_comboboxAllergiesActionPerformed

    private void btnSave_PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_PatientActionPerformed
        // TODO add your handling code here:
        patient.setPatientid(txtPatientID.getText());
        patient.setPrimarydoc(txtPrimaryDoc.getText());
        patient.setLastvisit(txtLastVisit.getText());
        patient.setNxtapt(txtNextVisit.getText());
        
        JOptionPane.showMessageDialog(this,"Patient Details are saved");
    }//GEN-LAST:event_btnSave_PatientActionPerformed

    private void comboboxOnMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxOnMedsActionPerformed
        // TODO add your handling code here:
        String selectedMValue = comboboxOnMeds.getSelectedItem().toString();
        patient.setOnmedication(selectedMValue);
    }//GEN-LAST:event_comboboxOnMedsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave_Patient;
    private javax.swing.JComboBox<String> comboboxAllergies;
    private javax.swing.JComboBox<String> comboboxOnMeds;
    private javax.swing.JLabel lblAllergies;
    private javax.swing.JLabel lblLastVisit;
    private javax.swing.JLabel lblNextVisit;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPrimaryDoc;
    private javax.swing.JLabel lblTitle_Patient;
    private javax.swing.JLabel lblonMedication;
    private javax.swing.JTextField txtLastVisit;
    private javax.swing.JTextField txtNextVisit;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrimaryDoc;
    // End of variables declaration//GEN-END:variables
}
