/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.VehicleRegistration;

/**
 *
 * @author Kunal
 */
public class VehicleRegJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VehicleRegJPanel
     */
    VehicleRegistration vehicle;
    public VehicleRegJPanel(VehicleRegistration vehicle) {
        initComponents();
        this.vehicle = vehicle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle_Vehicle = new javax.swing.JLabel();
        lblVehicleNo = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        btnSave_VehicleReg = new javax.swing.JButton();
        txtVehicleNo = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtSerialNo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(new javax.swing.border.MatteBorder(null));

        lblTitle_Vehicle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle_Vehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle_Vehicle.setText("Vehicle Registration");

        lblVehicleNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVehicleNo.setText("Vehicle Number:");

        lblModel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModel.setText("Vehicle Model:");

        lblSerialNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSerialNo.setText("Serial Number:");

        btnSave_VehicleReg.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSave_VehicleReg.setText("Save");
        btnSave_VehicleReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_VehicleRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle_Vehicle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehicleNo)
                            .addComponent(lblModel)
                            .addComponent(lblSerialNo))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnSave_VehicleReg)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle_Vehicle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleNo)
                    .addComponent(txtVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerialNo)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnSave_VehicleReg)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave_VehicleRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_VehicleRegActionPerformed
        // TODO add your handling code here:
        vehicle.setVehicleNo(txtVehicleNo.getText());
        vehicle.setModel(txtModel.getText());
        vehicle.setSerialNo(txtSerialNo.getText());
        
        JOptionPane.showMessageDialog(this,"Vehicle Registration Information is saved");
    }//GEN-LAST:event_btnSave_VehicleRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave_VehicleReg;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTitle_Vehicle;
    private javax.swing.JLabel lblVehicleNo;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
