/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package employeeUI;

/**
 *
 * @author apoorvdhaygude
 */
public class EmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeJPanel
     */
    public EmployeeJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnManageProf = new javax.swing.JButton();
        btnManageStudent = new javax.swing.JButton();
        btnTranscriptAuth = new javax.swing.JButton();
        btnDegreeAuth = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setBackground(new java.awt.Color(0, 153, 153));
        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("EMPLOYEE DASHBOARD");

        btnBack.setBackground(new java.awt.Color(204, 204, 0));
        btnBack.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblWelcome.setText("Welcome Admin !");

        btnManageProf.setBackground(new java.awt.Color(204, 204, 0));
        btnManageProf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnManageProf.setText("Professor Feedback");
        btnManageProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfActionPerformed(evt);
            }
        });

        btnManageStudent.setBackground(new java.awt.Color(204, 204, 0));
        btnManageStudent.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnTranscriptAuth.setBackground(new java.awt.Color(204, 204, 0));
        btnTranscriptAuth.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnTranscriptAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptAuthActionPerformed(evt);
            }
        });

        btnDegreeAuth.setBackground(new java.awt.Color(204, 204, 0));
        btnDegreeAuth.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnDegreeAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegreeAuthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(lblWelcome))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(btnManageProf)
                .addGap(48, 48, 48)
                .addComponent(btnManageStudent)
                .addGap(48, 48, 48)
                .addComponent(btnTranscriptAuth)
                .addGap(48, 48, 48)
                .addComponent(btnDegreeAuth)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDegreeAuth, btnManageProf, btnManageStudent, btnTranscriptAuth});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTranscriptAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDegreeAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 328, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageProfActionPerformed

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnTranscriptAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptAuthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranscriptAuthActionPerformed

    private void btnDegreeAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegreeAuthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDegreeAuthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDegreeAuth;
    private javax.swing.JButton btnManageProf;
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnTranscriptAuth;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
